import type { SetupBlueprint } from './types';

export const SMART_SCENARIOS: SetupBlueprint[] = [
  {
    id: 'indie_school_drink',
    name: '自主饮品-学校门口',
    description: '高人流饮品场景，验证增长和供给平衡。',
    brandId: 'independent',
    locationId: 'school',
    addressId: 'school_gate',
    decorationId: 'modern',
    productIds: ['milktea', 'fruittea', 'dessert'],
    staffPlan: [
      { staffTypeId: 'fulltime', task: 'chef' },
      { staffTypeId: 'fulltime', task: 'waiter' },
      { staffTypeId: 'parttime', task: 'cleaner' },
    ],
    startSeason: 'spring',
  },
  {
    id: 'indie_community_meal',
    name: '自主餐食-社区店',
    description: '家庭客群稳定场景，验证复购和口碑积累。',
    brandId: 'independent',
    locationId: 'community',
    addressId: 'community_market',
    decorationId: 'cozy',
    productIds: ['ricebox', 'noodles', 'dessert'],
    staffPlan: [
      { staffTypeId: 'fulltime', task: 'chef' },
      { staffTypeId: 'fulltime', task: 'chef' },
      { staffTypeId: 'parttime', task: 'waiter' },
    ],
    startSeason: 'autumn',
  },
  {
    id: 'luckin_office_coffee',
    name: '瑞幸-写字楼咖啡',
    description: '高客单写字楼模型，验证品牌+履约对平台的影响。',
    brandId: 'luckin',
    locationId: 'office',
    addressId: 'office_lobby',
    decorationId: 'premium',
    productIds: ['coffee', 'fruittea'],
    staffPlan: [
      { staffTypeId: 'fulltime', task: 'chef' },
      { staffTypeId: 'fulltime', task: 'waiter' },
      { staffTypeId: 'parttime', task: 'cleaner' },
    ],
    startSeason: 'winter',
  },
  {
    id: 'mixue_school_fast',
    name: '蜜雪-校园快流量',
    description: '强品牌低价场景，验证是否出现过快双100。',
    brandId: 'mixue',
    locationId: 'school',
    addressId: 'school_canteen',
    decorationId: 'simple',
    productIds: ['milktea', 'fruittea'],
    staffPlan: [
      { staffTypeId: 'fulltime', task: 'chef' },
      { staffTypeId: 'parttime', task: 'waiter' },
      { staffTypeId: 'parttime', task: 'marketer' },
    ],
    startSeason: 'summer',
  },
  {
    id: 'tastien_business_delivery',
    name: '塔斯汀-商圈外卖导向',
    description: '重外卖策略，验证平台曝光是增减双向而非单向上涨。',
    brandId: 'tastien',
    locationId: 'business',
    addressId: 'business_street',
    decorationId: 'modern',
    productIds: ['burger', 'fries', 'dessert'],
    staffPlan: [
      { staffTypeId: 'fulltime', task: 'chef' },
      { staffTypeId: 'fulltime', task: 'chef' },
      { staffTypeId: 'fulltime', task: 'waiter' },
      { staffTypeId: 'parttime', task: 'marketer' },
    ],
    startSeason: 'spring',
  },
  {
    id: 'risk_probe_high_cost',
    name: '快招风险探针',
    description: '高风险品牌压测，用于验证失败路径是否合理可解释。',
    brandId: 'yogurt',
    locationId: 'tourist',
    addressId: 'tourist_parking',
    decorationId: 'modern',
    productIds: ['milktea', 'fruittea', 'dessert'],
    staffPlan: [
      { staffTypeId: 'fulltime', task: 'chef' },
      { staffTypeId: 'fulltime', task: 'waiter' },
      { staffTypeId: 'parttime', task: 'cleaner' },
    ],
    startSeason: 'winter',
  },
];
